Fixed SyntaxError.
This error was the following:
  File "./libmodernize/fixes/fix_import.py", line 25
SyntaxError: Non-ASCII character '\xe2' in file ./libmodernize/fixes/fix_import.py on line 25, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
This was caused by introducing non-ASCII quotes.